### ISSUE TITLE
Checklist forward mapping to HDF

### ISSUE THREAD

**Issue by Hookwitz** [mitre/heimdall2#4204]
HDF-Converters should be updated to include a CKL -> HDF converter. This new functionality should then been connected to SAF-CLI and Heimdall having a single source of functionality. Currently neither have the forward conversion functionality, however, both have a reverse map that is individual to both.

Ideally, the forward mapping will use the JSONIX library making use of the marshall and unmarshall functions to make bi-directional conversion easier.

The forward mapper should be written to ingest the permutations of the Checklist schema provided by DISA Stig Viewer.
The final product should be connected to/or connectable to:

- [ ] Heimdall frontend - viewable as a results object
- [ ] Heimdall API
- [ ] SAF-CLI

Identified the edge cases:

Use Inspec to create new like and compare how XCCDF uses wrapper/overlay profiles
- [ ] Multiple STIG Checklist
- [ ] Filtered-Multiple STIG Checklist

**Comment by Hookwitz** [comment]
Something to think about and possible add in the hdf -> ckl:

When exporting to CKL the caveat, rationale, justification, and comments should be combined and added to the comments tag. The mapper from ckl -> hdf should be able to parse and handle the format.
